"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import char

class camera_t(object):
    __slots__ = ["utime", "dist", "theta", "color"]

    def __init__(self):
        self.utime = 0
        self.dist = 0.0
        self.theta = 0.0
        self.color = char()

    def encode(self):
        buf = BytesIO()
        buf.write(camera_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qff", self.utime, self.dist, self.theta))
        assert self.color._get_packed_fingerprint() == char._get_packed_fingerprint()
        self.color._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != camera_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return camera_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = camera_t()
        self.utime, self.dist, self.theta = struct.unpack(">qff", buf.read(16))
        self.color = char._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if camera_t in parents: return 0
        newparents = parents + [camera_t]
        tmphash = (0xc70483156799d86c+ char._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if camera_t._packed_fingerprint is None:
            camera_t._packed_fingerprint = struct.pack(">Q", camera_t._get_hash_recursive([]))
        return camera_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

